# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("browser.bookmarks", "");
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("dom.apps.reset-permissions", true);
user_pref("gecko.buildID", "");
user_pref("gecko.mstone", "");
user_pref("gfx.crash-guard.d3d11layers.appVersion", "45.0.1");
user_pref("gfx.crash-guard.d3d11layers.deviceID", "0x5916");
user_pref("gfx.crash-guard.d3d11layers.driverVersion", "21.20.16.4627");
user_pref("gfx.crash-guard.d3d11layers.feature-d2d", true);
user_pref("gfx.crash-guard.d3d11layers.feature-d3d11", true);
user_pref("gfx.crash-guard.glcontext.gfx.driver-init.direct3d11-angle", true);
user_pref("gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle", true);
user_pref("gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-d3d11", false);
user_pref("gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-force-warp", false);
user_pref("gfx.crash-guard.glcontext.gfx.driver-init.webgl-angle-try-d3d11", true);
user_pref("gfx.crash-guard.status.d3d11layers", 2);
user_pref("gfx.crash-guard.status.d3d9video", 1);
user_pref("gfx.crash-guard.status.glcontext", 2);
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("idle.lastDailyNotification", 1505397729);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1501456592);
user_pref("places.history.expiration.transient_current_max_pages", 33785);
user_pref("plugin.importedState", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1501456592);
